#!/usr/bin/env python3
import platform as p
print(platform.system())
print(platform.node())
print(platform.platform())
print(platform.release())
print(platform.uname())
# print(platform.system_alias())
print(platform.python_version_tuple())
print(platform.machine())
print(platform.dist())
print(platform.release())
print(platform.architecture())
print(platform.processor())
print(platform.machine())
print(platform.machine())
