class Test:
    def __init__(self):
        print("COnstructor")
    
    def m1(self,x):
        print("The x value is: ", x)
t = Test()
# t.m1(10)
print("__dict__: ", Test.__dict__)
print("__base__: ", Test.__base__)
print("__bases__: ", Test.__bases__)
print("__annotations__: ", Test.__annotations__)
print("__call__: ", Test.__call__)
print("__class__: ", Test.__class__)
print("__delattr__: ", Test.__delattr__)
print("__dictoffset__: ", Test.__dictoffset__)
print("__doc__: ", Test.__doc__)
print("__dir__: ", Test.__dir__)

print("__flags__: ", Test.__flags__)
print("__format__: ", Test.__format__)
print("__getattribute__: ", Test.__getattribute__)
print("__getstate__: ", Test.__getstate__)
print("__hash__: ", Test.__hash__)
print("__init__: ", Test.__init__)
print("__init_subclass__: ", Test.__init_subclass__)
print("__instancecheck__: ", Test.__instancecheck__)
print("__itemsize__: ", Test.__itemsize__)
print("__module__: ", Test.__module__)
print("__mro__: ", Test.__mro__)
print("__name__: ", Test.__name__)
print("__ne__: ", Test.__ne__)
print("__new__: ", Test.__new__)
print("__or__: ", Test.__or__)
print("__prepare__: ", Test.__prepare__)
print("__qualname__: ", Test.__qualname__)
print("__reduce__: ", Test.__reduce__)
print("__reduce_ex__: ", Test.__reduce_ex__)
print("__repr__: ", Test.__repr__)
print("__ror__: ", Test.__ror__)
print("__setattr__: ", Test.__setattr__)
print("__sizeof__: ", Test.__sizeof__)
print("__str__: ", Test.__str__)
print("__subclasscheck__: ", Test.__subclasscheck__)
print("__subclasses__: ", Test.__subclasses__)
print("__subclasshook__:", Test.__subclasshook__)
print("__text_signature__: ", Test.__text_signature__)
print("__weakrefobject__: ", Test.__weakrefobject__)
print("__eg__: ", Test.__eg__)